In [2]:
import pandas as pd

In [5]:
df = pd.read_excel("D:\Voltride_Analysis_DecodeX\modified_voltride_dataset_DecodeX.xlsx")
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\V'
<>:1: SyntaxWarning: invalid escape sequence '\V'
C:\Users\TAMILARASU\AppData\Local\Temp\ipykernel_16136\814910607.py:1: SyntaxWarning: invalid escape sequence '\V'
  df = pd.read_excel("D:\Voltride_Analysis_DecodeX\modified_voltride_dataset_DecodeX.xlsx")

,City,Date,Day,Hour,Pickup_Zone,Drop_Zone,Ride_Distance_km,Estimated_Fare,Surge_Multiplier,EV_Battery_%,Driver_Available,Charging_Station_Nearby,Weather,Ride_Status,Cancellation_By,Cancellation_Flag,Completion_Flag,Low_Battery,Peak_Hour
0,Hyderabad,2025-01-01,Wednesday,5,8,3,21.59,374.64,2.0,29,Yes,Yes,Heavy Rain,Completed,Not_Cancelled,0,1,0,0
1,Mumbai,2025-01-01,Wednesday,13,5,4,4.70,353.66,1.0,61,Yes,No,Rain,Completed,Not_Cancelled,0,1,0,0
2,Delhi,2025-01-01,Wednesday,11,5,5,3.52,329.88,2.0,30,Yes,Yes,Clear,Completed,Not_Cancelled,0,1,0,0
3,Bengaluru,2025-01-01,Wednesday,22,9,7,21.28,628.14,2.0,17,Yes,Yes,Clear,Cancelled,System,1,0,1,0
4,Hyderabad,2025-01-01,Wednesday,19,5,2,7.00,526.89,1.5,34,Yes,No,Rain,Completed,Not_Cancelled,0,1,0,1

In [7]:
df["Revenue"] = df.apply(
    lambda x: x["Estimated_Fare"] if x["Ride_Status"] == "Completed" else 0,
    axis=1
)

df.head()

,City,Date,Day,Hour,Pickup_Zone,Drop_Zone,Ride_Distance_km,Estimated_Fare,Surge_Multiplier,EV_Battery_%,Driver_Available,Charging_Station_Nearby,Weather,Ride_Status,Cancellation_By,Cancellation_Flag,Completion_Flag,Low_Battery,Peak_Hour,Revenue
0,Hyderabad,2025-01-01,Wednesday,5,8,3,21.59,374.64,2.0,29,Yes,Yes,Heavy Rain,Completed,Not_Cancelled,0,1,0,0,374.64
1,Mumbai,2025-01-01,Wednesday,13,5,4,4.70,353.66,1.0,61,Yes,No,Rain,Completed,Not_Cancelled,0,1,0,0,353.66
2,Delhi,2025-01-01,Wednesday,11,5,5,3.52,329.88,2.0,30,Yes,Yes,Clear,Completed,Not_Cancelled,0,1,0,0,329.88
3,Bengaluru,2025-01-01,Wednesday,22,9,7,21.28,628.14,2.0,17,Yes,Yes,Clear,Cancelled,System,1,0,1,0,0.00
4,Hyderabad,2025-01-01,Wednesday,19,5,2,7.00,526.89,1.5,34,Yes,No,Rain,Completed,Not_Cancelled,0,1,0,1,526.89

In [8]:
total_revenue = df["Revenue"].sum()

print("Total Revenue:", round(total_revenue, 2))

Total Revenue: 801615.63

In [9]:
driver_payout = total_revenue * 0.70

print("Driver Payout (70%):", round(driver_payout, 2))

Driver Payout (70%): 561130.94

In [10]:
completed_rides = df[df["Ride_Status"] == "Completed"].shape[0]

charging_cost = completed_rides * 20

print("Charging Cost:", charging_cost)

Charging Cost: 35220

In [11]:
net_profit = total_revenue - driver_payout - charging_cost

print("Net Profit:", round(net_profit, 2))

Net Profit: 205264.69

In [12]:
profit_margin = (net_profit / total_revenue) * 100

print("Profit Margin (%):", round(profit_margin, 2))

Profit Margin (%): 25.61

In [13]:
df["Month_Name"] = df["Date"].dt.month_name()

monthly_revenue = df.groupby("Month_Name")["Revenue"].sum().reset_index()

monthly_revenue

  Month_Name    Revenue
0      April  103836.10
1   February  214675.97
2    January  247593.32
3      March  235510.24

In [14]:
monthly_revenue["Driver_Payout"] = monthly_revenue["Revenue"] * 0.70

monthly_revenue["Charging_Cost"] = (
    df[df["Ride_Status"] == "Completed"]
    .groupby(df["Date"].dt.month_name())
    .size()
    .values * 20
)

monthly_revenue["Net_Profit"] = (
    monthly_revenue["Revenue"]
    - monthly_revenue["Driver_Payout"]
    - monthly_revenue["Charging_Cost"]
)

monthly_revenue

  Month_Name    Revenue  Driver_Payout  Charging_Cost  Net_Profit
0      April  103836.10      72685.270           4660   26490.830
1   February  214675.97     150273.179           9560   54842.791
2    January  247593.32     173315.324          10640   63637.996
3      March  235510.24     164857.168          10360   60293.072

# save the dataframe as Excel file

In [17]:
monthly_revenue.to_excel("Financial_Performance_Report.xlsx", index=False)